version: '3.7'
services:
  server:
    build: .
    command: npm run start:dev
    ports: 
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/app:rw
      - /app/node_modules

  database:
    image: mongo
    volumes:
      - db-volume:/data/db
  
  redis: 
    image: redis:7.0 

volumes:
    db-volume:
