version: '3.7'
services:
  server:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/app:rw
      - /app/node_modules

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-volume:/data/db
  
  redis: 
    image: redis:7.0
    ports:
      - 6379:6379    

volumes:
    db-volume:
